### Info: https://gohugo.io/content-management/multilingual/#configure-languages

#[en]
  #languageName = "English"
  #languageFlag = "ğŸ‡¬ğŸ‡§"
  #languageCode = "en"
  #languageCodeCountry = "DO_NOT_USE"
  #timeZone = "Etc/UTC"
  #weight = 110

[en-ph]
  languageName = "English (PH)"
  languageFlag = "ğŸ‡µğŸ‡­"
  languageCode = "en-PH"
  languageCodeCountry = "ph"
  timeZone = "Asia/Manila"
  weight = 111
  #[[en-ph.menu.main]]
    #name              = "Home"
    #identifier        = "home"
    #url               = "/"
    #pre               = "home"
    #weight            = 1
    #[en-ph.menu.main.params]
      #newTab = false

#[fil]
  #languageName = "Filipino"
  #languageFlag = "ğŸ‡µğŸ‡­"
  #languageCode = "fil"
  #languageCodeCountry = "ph"
  #timeZone = "Asia/Manila"
  #weight = 120
  #title = ""
  #[fil.params]
    #description = ""     # IMPT for Schema.org; OpenGraph; Twitter Cards -- for RDFa, Microdata, JSON-LD

#[tl-tglg]
  #languageName = "Tagalog Baybayin"
  #languageFlag = "ğŸ‡µğŸ‡­"
  #languageCode = "tl-Tglg"
  #languageCodeCountry = "ph"
  #timeZone = "Asia/Manila"
  #weight = 121
  #title = ""
  #[tl.tglg.params]
    #description = ""     # IMPT for Schema.org; OpenGraph; Twitter Cards -- for RDFa, Microdata, JSON-LD

#[zh-hant]
  #languageName = "ä¸­æ–‡ï¼ˆç¹é«”ï¼‰"
  #languageFlag = "ğŸ‡¨ğŸ‡³"
  #languageCode = "zh-Hant"
  #languageCodeCountry = "cn"
  #timeZone = "Asia/Shanghai"
  #weight = 130
  #title = ""
  #[zh-hant.params]
    #description = ""     # IMPT for Schema.org; OpenGraph; Twitter Cards -- for RDFa, Microdata, JSON-LD

#[zh-hans]
  #languageName = "ä¸­æ–‡ï¼ˆç®€ä½“ï¼‰"
  #languageFlag = "ğŸ‡¨ğŸ‡³"
  #languageCode = "zh-Hans"
  #languageCodeCountry = "cn"
  #timeZone = "Asia/Shanghai"
  #weight = 131
  #title = ""
  #[zh-hans.params]
    #description = ""     # IMPT for Schema.org; OpenGraph; Twitter Cards -- for RDFa, Microdata, JSON-LD

[ja]
  languageName = "æ—¥æœ¬èª"
  languageFlag = "ğŸ‡¯ğŸ‡µ"
  languageCode = "ja"
  languageCodeCountry = "jp"
  timeZone = "Asia/Tokyo"
  weight = 140
  title = ""
  [ja.params]
    description = "ç§ãŸã¡ã¯é›¢ã‚ŒãŸçµŒå…¸ã‚’ç ”ç©¶ã—ã€ä¸–ä»£ã‚’è¶…ãˆã¦å—ã‘ç¶™ãŒã‚Œã¦ããŸå˜˜ã‹ã‚‰è‡ªåˆ†è‡ªèº«ã‚’è§£æ”¾ã™ã‚‹ã“ã¨ãŒä½•ã§ã‚ã‚Œã€çœŸå®Ÿã‚’å—ã‘å…¥ã‚Œã¾ã™ã€‚"     # IMPT for Schema.org; OpenGraph; Twitter Cards -- for RDFa, Microdata, JSON-LD

[ko]
  languageName = "í•œêµ­ì–´"
  languageFlag = "ğŸ‡°ğŸ‡·"
  languageCode = "ko"
  languageCodeCountry = "kr"
  timeZone = "Asia/Seoul"
  weight = 150
  title = ""
  [ko.params]
    description = "ìš°ë¦¬ëŠ” êµ¬ë³„ëœ ì„±ê²½ì„ ê³µë¶€í•˜ê³  ëŒ€ëŒ€ë¡œ ì „í•´ ë‚´ë ¤ì˜¤ëŠ” ê±°ì§“ì—ì„œ ë²—ì–´ë‚˜ê¸° ìœ„í•´ ë¬´ì—‡ì´ë“ ì§€ ì§„ë¦¬ë¥¼ ë°›ì•„ë“¤ì…ë‹ˆë‹¤."     # IMPT for Schema.org; OpenGraph; Twitter Cards -- for RDFa, Microdata, JSON-LD
