# See: https://gohugo.io/getting-started/configuration/#merge-configuration-from-themes
_merge = "deep"

# YourOnly.One: Do not use mainSections, it's conflicting with the hugo-theme-stack theme.
mainSections = ["blog", "posts"]                                             # Hugo default

favicon_mstilecolor = "#603cba"

### BGN: Structured Data ###
  siteStartYear = "2007"
  description = "We study the set-apart scripture and accept the truth whatever it might be to free ourselves from the lies that were passed down through generations."
  keywords = ["One Way Faith", "ä¸€æ–¹é€šè¡Œä¿¡ä»°", "ä¸€æ–¹å‘ã®ä¿¡ä»°", "ì¼ë°©í†µí–‰ì‹ ì•™", "í¸ë„ ì‹ ì•™", "The Natsari Way", "Way of Believers", "YourOnlyOne", "YourOnly.One", "Yahuhanan Yukiya Sese Cuneta", "Yuki", "YoHan", "Yo-Han",  "×™×”×•×—× ×Ÿ", "áœŒáœ“áœƒáœ’", "ì‚¬ìš”í•œ", "è¬é›ªçŸ¢ï¼ˆã‚†ãã‚„ï¼‰", "ìŠ¤ë…¸", "Seu-No", "SeuNo", "Snow", "Yohanan", "áœŒáœ“áœ‘áœˆáœˆáœ”", "áœŒáœ“áœ‘áœˆáœˆáœ•", "áœŒáœ‘áœ“áœ‘áœˆáœˆáœ”", "áœŒáœ‘áœ“áœ‘áœˆáœˆáœ•"] # Can be overriden per page
  images = ["https://img.youronly.one/works/FlagMenorah-Proto-(CC0).webp", "https://img.youronly.one/works/FlagMenorah-Paleo-(CC0).webp"]
### END: Structured Data ###

### BGN: Theme Settings ###
  #featuredImageField = ""
  rssFullContent = true
  #favicon = ""

  [footer]
    since = "2009"
    #customText = ""

  [dateFormat]
    published = "2006-01-02 15:04"
    lastUpdated = "2006-01-02 15:04"

  [sidebar]
    compact = false
    emoji = "ğŸ›"
    subtitle = "Be a Berean"
    [sidebar.avatar]
      enabled = true
      local = false
      src = "https://rsc.youronly.one/img/y/Way-Hanukkahns4.svg"

  [article]
    math = false
    toc = true
    readingTime = true
    [article.license]
      enabled = false
      #default = "CHANGE_THIS"             # We do not need this.

  [comments]
    enabled = true
    provider = "disqus"

    [comments.disqusjs]
      shortname = "youronlyone"

  [[widgets.homepage]]
  type = "search"

  #[[widgets.homepage]]
  #type = "archives"
  #  [widgets.homepage.params]
  #  limit = "7"

  [[widgets.homepage]]
  type = "series"
    [widgets.homepage.params]
    limit = "7"

  [[widgets.homepage]]
  type = "categories"
    [widgets.homepage.params]
    limit = "7"

  [[widgets.homepage]]
  type = "tag-cloud"
    [widgets.homepage.params]
    limit = "7"

  [[widgets.page]]
  type = "search"

  [[widgets.page]]
  type = "toc"

  [[widgets.page]]
  type = "partofseries"

  #[[widgets.page]]
  #type = "archives"
  #  [widgets.page.params]
  #  limit = "7"

  [[widgets.page]]
  type = "series"
    [widgets.page.params]
    limit = "7"

  [[widgets.page]]
  type = "categories"
    [widgets.page.params]
    limit = "7"

  [[widgets.page]]
  type = "tag-cloud"
    [widgets.page.params]
    limit = "7"

  [colorScheme]
    toggle = false
    default = "dark"

  [imageProcessing.cover]
    enabled = true
  [imageProcessing.content]
    enabled = true
### END: Theme Settings ###

### BGN: Other Settings ###
  [semweb]
    datecreated = "2007-04-06"
    isblog = true
    sameas = [
      "https://www.facebook.com/youronly.ONE.WAY",
      "https://c.im/@YourOnlyOne",
      "https://pixelfed.social/YourOnlyOne",
      "https://www.youtube.com/@YourOnlyOneOfcl",
      "https://www.facebook.com/YourOnly.ONE.ofcl"
    ]

  [tools]
    #onesignal = "79058a23-5e2c-4862-926f-37d20de118e5"
### END: Other Settings ###
